### ISSUE TITLE
UAS v3 ToDo List and issues with stylesheets

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#327]
ToDo List :)

- [x] 1. Log Viewer ... line spacing is off because the first column (line numbers) is too narrow (only effects the Plex Media Server.log and larger log files for some reason).
- [x] 2. Change of text requested. Current warning text "It's not recommended to view files this large in the browser (15.000 LINES+). If you want to view the whole file go download it." I propose this text instead "We recommend you download large files over 15,000 lines long and view them in your favourite text editor." 
- [x] 3. UAS Module select (search box) overlay is overlaid on the scrollbar in FF (see image below).
- [x] 4. FindMedia MIA #302 (Not yet done but will come)
- [x] 5. Subtitles ... search does not indicate that any results have been returned until clicking in a relevant library. #317
- [ ] 6. No way to clear search results without removing the search terms

Chrome Version 59.0.3071.86 (Official Build) (64-bit) does not render the style sheet correctly. As you may see in the second image below, the menu item background colours are not rendered correctly as well as the title bar text colours.

Also the manual install button colours are ignored, but the hover colours are not, they render correctly for both the button and menu items.

Same issues as Chrome using Microsoft Edge, colours for menu items and buttons not being honoured.

See the image below for details of missing classes.
![untitled-1](https://user-images.githubusercontent.com/12381786/27002959-0093f09a-4e31-11e7-9361-28c5bd117886.jpg)

![untitled-2](https://user-images.githubusercontent.com/12381786/27002962-113444c2-4e31-11e7-8067-0af0c0cb194c.jpg)

Stylesheet Sample here: https://1drv.ms/u/s!Al6fiSgXZz8chKF4TxM7VSmtN1uMgw

**Comment by ukdtom** [comment]
[AussieStyle.zip](https://github.com/ukdtom/WebTools.bundle/files/1065864/AussieStyle.zip)

CSS uploaded to this GHI as a zip :-P

**Comment by trumpy81** [comment]
Smarty, I tried both FF and Chrome, no go :(

**Comment by creoludifico** [comment]
Hello @trumpy81 

Thank you for the input.
As you already noticed WebTools are not ready for styling yet. I still have a few technical issues to fix on the UAS before checking up with CSS templates.

**Comment by trumpy81** [comment]
I certainly can appreciate the difficulties you face, but I thought I would simply give you a heads up on where things are now and hopefully give you some direction.

The non-compliance of Chrome and Edge certainly don't help matters and I hope that it wont create too much of a problem for you.

And don't forget to give smarty pants up there, a hard time when you need to ... lol 👍

**Comment by ukdtom** [comment]
I heard that ;-)

**Comment by creoludifico** [comment]
Should be fixed

**Comment by ukdtom** [comment]
Andy?

**Comment by trumpy81** [comment]
The items listed in my first post, except for number 6 have been corrected and can be crossed off the list. :)

The issues with Chrome and Edge not honouring the style sheet correctly remains. :(

**Comment by ukdtom** [comment]
Thanks...

Oliver?

**Comment by trumpy81** [comment]
An addendum for the todo list.

1. FindMedia missing ? button (all browsers)
2. Log Viewer missing ? button (all browsers)
3. When WebTools is first loaded and you go to UAS, the search box contains [!} undefined text until you go to Language and click on the force update button. (all browsers)
4. No upload Playlist function :(
5. No changes in Chrome or Edge as far as the non honoured css is concerned.
5. No elements have been exposed in the default style sheet for the following sections: UAS, FindMedia, Playlists.

Otherwise, everything else is looking good guys, keep up the good work!

**Comment by trumpy81** [comment]
You can ignore 6. on the revised list, I managed to uncover all of the elements I need. I should have some themes completed over the next few days, fingers crossed. :)

Still have issues with Chrome and Edge not following the .css style sheets though.

**Comment by ukdtom** [comment]
@creoludifico ?????

**Comment by creoludifico** [comment]
Yes for now
